### DISCUSSION TITLE
How to add caching to format GitHub action

### DISCUSSION THREAD

**Discussion by kgrigsby59** [pointfreeco/swift-composable-architecture#1179] [Q&A]
I'm using a GitHub action just like.github/workflows/format.yml in this repo. Can someone show me how to cache the swift-format tool? It takes about 6 mins to build and everything else is seconds. I tried this 
```      
    - name: Cache swift-format
        id: cache-swift-format
        uses: actions/cache@v3
        with:
          key: swift-format-build
          path: .build

    - name: Install
        if: steps.cache-swift-format.outputs.cache-hit != 'true'
        run: brew install Formulae/swift-format@5.6
```
but got the warning ```Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.```
The output from the Install step is:
```
Run brew install Formulae/swift-format@5.6
[4]==>Cloning https://github.com/apple/swift-format.git
[5]Cloning into '/Users/runner/Library/Caches/Homebrew/swift-format@5.6--git'...
[6]==>Checking out branch release/5.6
[7]Already on 'release/5.6'
[8]Your branch is up to date with 'origin/release/5.6'.
[9]==>Installing swift-format@5.6 from kgrigsby59/formulae
[10]==>swift build -c release --disable-sandbox --build-path '.build'
[11]🍺  /usr/local/Cellar/swift-format@5.6/5.6: 5 files, 15.9MB, built in 6 minutes 38 seconds
[12]==>Running `brew cleanup swift-format@5.6`...
[13]Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
[14]Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

**Comment by pchelnikov** [comment]
@kgrigsby59 did you solve this?

**Reply by kgrigsby59** [reply]
This is what I'm using: 
```
name: Format

on:
  push:
    branches:
      - 'feature/async'

jobs:
  swift_format:
    name: swift-format
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3

      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_13.4.1.app

      - name: Restore swift build cache
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-5.6-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-5.6-
            
      - name: swift build
        run: |
          if [ -d ".build" ]; then
            if ! [ -x "$(command -v swift-format)" ]; then
              sudo cp -f .build/release/swift-format /usr/local/bin/swift-format
            fi
          else
            git clone -b release/5.6 https://github.com/apple/swift-format.git
            cd swift-format
            swift build --disable-sandbox -c release
            mv .build .. && cd ..
            sudo cp -f .build/release/swift-format /usr/local/bin/swift-format
          fi
          
      - name: Format
        run: swift-format --ignore-unparsable-files --in-place --recursive ./QuartersKit ./QuarterMinder-TCA ./QuarterMinderWidget ./QuarterMinder-TCAUITests
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift-format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
